name: Sync Fork

on:
  schedule:
    - cron: '* 13 * * *' # every day at 13 hours
  workflow_dispatch: # on button click

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v1.8
        with:
          owner: openpmix
          token: ${{ secrets.GITHUB_TOKEN }}
          base: master
          head: master
          auto_merge: false
          auto_approve: false
          ignore_fail: true

          
